---
# ---------------------------------------------------------------------------------------------------
# File: 301-sg.yaml
# Version: 3.0
# Library: https://github.com/Frankie116/my-library.git
# Summary: Creates a Security Group.  User can choose an existing VPC when creating this stack.
#
# Dependant stacks created from code located in s3:
# None,  but this stack requires an existing vpc with at least 2 public subnets.
# ---------------------------------------------------------------------------------------------------

AWSTemplateFormatVersion: 2010-09-09
Description: This template creates a security group in an existing vpc.  The code is part of a standard modular infrastructure library.

## ----------------------------------------------------------------------
Parameters:

  SgVpc:
    Type: AWS::EC2::VPC::Id
    Default: MainVpc

  SgListenerPort:
    Type: Number
    Default: 80

  SgSourceIp1:
    Type: String
    Default: 0.0.0.0/0

  SgSourceIp2:
    Type: String
    Default: 0.0.0.0/0
    
## ----------------------------------------------------------------------
Resources:

  SgAlb:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable access on ports 80/443
      VpcId: !Ref SgVpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref SgListenerPort
          ToPort: !Ref SgListenerPort
          CidrIp: !Ref SgSourceIp1
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref SgSourceIp2
      Tags:
        - Key: Name
          Value: Security Group

# ----------------------------------------------------------------------
Outputs:

  SgVpc:
    Description: Vpc ID
    Value: !Ref SgVpc
    Export:
      Name: !Sub ${AWS::StackName}-SgVpc

  SgAlb:
    Description: Security Group ID
    Value: !GetAtt SgAlb.GroupId
    Export:
      Name: !Sub ${AWS::StackName}-SgAlb
    

  SgListenerPort:
    Description: Application Load Balancer Security Group ID
    Value: !Ref SgListenerPort
    Export:
      Name: !Sub ${AWS::StackName}-SgListenerPort
    


  