---
# ---------------------------------------------------------------------------------------------------
# File: 302-alb.yaml
# Version: 3.0
# Library: https://github.com/Frankie116/my-library.git
# Summary: Creates an application load balancer and an alb security group using nested stacks. 
# User can choose an existing VPC when creating this stack.
#
# Dependant stacks created from code located in s3:
# 301-sg.yaml
# ---------------------------------------------------------------------------------------------------

AWSTemplateFormatVersion: 2010-09-09
Description: This template creates an alb & security groups (nested).  The code is part of a standard modular infrastructure library.

## ----------------------------------------------------------------------
Metadata:

  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - 
        Label: 
          default: "Vpc"
        Parameters: 
          - AlbVpc
          - AlbSubnets
      - 
        Label: 
          default: "Security Group"
        Parameters: 
          - AlbListenerPort
          - AlbSourceIp1
          - AlbSourceIp2

## ----------------------------------------------------------------------
Parameters:

  AlbVpc:
    Type: AWS::EC2::VPC::Id
    Default: MainVpc

  AlbSubnets:
    Type: List<AWS::EC2::Subnet::Id>

  AlbListenerPort:
    Type: Number
    Default: 80

  AlbSourceIp1:
    Type: String
    Default: 0.0.0.0/0

  AlbSourceIp2:
    Type: String
    Default: 0.0.0.0/0

## ----------------------------------------------------------------------
Resources:

  NestedSg:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        SgListenerPort: !Ref AlbListenerPort
        SgSourceIp1: !Ref AlbSourceIp1
        SgSourceIp2: !Ref AlbSourceIp2
        SgVpc: !Ref AlbVpc
      TemplateURL: https://my-cloudformation-repo.s3.eu-west-2.amazonaws.com/unified-stacks/app3/301-sg.yaml

  Alb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    DependsOn: NestedSg
    Properties:
      Name: MyAlb
      SecurityGroups: 
          - !GetAtt NestedSg.Outputs.SgAlb
      Subnets: !Ref AlbSubnets

       
# ----------------------------------------------------------------------
Outputs:

  SgStackRef:
    Value: !Ref NestedSg

  SgAlb:
    Description: Security Group ID
    Value: !GetAtt NestedSg.Outputs.SgAlb
    Export:
      Name: !Sub ${AWS::StackName}-SgAlb

  Alb:
    Description: Alb ID
    Value: !Ref Alb
    Export:
      Name: !Sub ${AWS::StackName}-Alb

  AlbDnsName:
    Description: Alb DNS Name
    Value: !GetAtt Alb.DNSName
    Export:
      Name: !Sub ${AWS::StackName}-AlbDnsName

  AlbZoneID:
    Description: Alb Canonical Hosted Zone ID
    Value: !GetAtt Alb.CanonicalHostedZoneID
    Export:
      Name: !Sub ${AWS::StackName}-AlbZoneID

  